############# English navigation ##############

# main menu
[[main]]
name = "Home"
pageRef = "/"
weight = 1

[[main]]
weight = 2
name = "Blog"
pageRef = "/blog"

[[main]]
name = "About"
pageRef = "/about"
weight = 3